platform :ios, '8.0'

inhibit_all_warnings!

def app_pods
    pod 'FLEX', :configurations => ['Debug']
    #pod 'Reveal-iOS-SDK','~> 1.6.2', :configurations => ['Debug']
    #pod 'FBMemoryProfiler', '0.1.3', :configurations => ['Debug']
end

def app_pods_simulator
    app_pods
    #Can add individual pods
end

target 'ASDKTestOn4S' do
    app_pods
end

#target 'ASDKTestOn4S-simulator' do
#    app_pods_simulator
#end

### HOOK POST
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_STRICT_OBJC_MSGSEND'] = 'NO'
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
