#source 'git@gitlab.51y5.net:LSNTouTiaoSDK/LSNTouTiaoSpec.git'
source 'https://github.com/artsy/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

inhibit_all_warnings!

def app_pods
    pod 'FLEX', :configurations => ['Debug']
    pod 'Masonry'
    pod 'MLeaksFinder'
#    pod 'LSUtilities'
#    pod 'SDWebImage'
#    pod 'SDWebImage/WebP'
end

target 'MyTestIO' do
    app_pods
    
    #Can add individual pods
end

#Have serveral targets may need this 'def
def common_pods
    
end

### HOOK POST
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_STRICT_OBJC_MSGSEND'] = 'NO'
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
